apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_deployment
  labels:
    app: hello_world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello_world
  template:
    metadata:
      labels:
        app: hello_world
    spec:
      containers:
      - name: samleimg
        image: samleimg:latest
        ports:
        - containerPort: 80