apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: development
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: samleimg
        image: sampler.azurecr.io/samleimg:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
       - name: acrcred